### ISSUE TITLE
Remove the use of JSON file as output

### ISSUE THREAD

**Issue by Minitour** [Minitour/wapy-camera-service#3]
We do not want to output the file into JSON format. Reading and writing to disk file is not efficient and will result with a massive large amount of files.

We need instead to write to a messaging queue. Given that the messaging queue is not available, we will write to disk using in memory database or SQLite.

Once the network is back (the queue is again reachable) we will unload everything from the local storage.

**Comment by TomerGoldfeder** [comment]
Done
